version: "3.9"
services:
  discovery:
    build: ./discovery-server
    ports:
      - "8761:8761"
    image: "discovery-service"
  candidat:
    build: ./candidaProject
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8081:8081"
    image: "candidate-service"
